--------------------------------------------------------
--  DDL for Table XXCL
--------------------------------------------------------

  CREATE TABLE "MYSCHEMA"."XXCL" 
   (	"ID" RAW(16), 
	"NAME" NVARCHAR2(10), 
	"CREATED" DATE, 
	"UPDATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MYTABLESPACE" ;
--------------------------------------------------------
--  DDL for Table XXCO
--------------------------------------------------------

  CREATE TABLE "MYSCHEMA"."XXCO" 
   (	"ID" RAW(16), 
	"CREATED" DATE, 
	"UPDATED" DATE, 
	"VALUE" NUMBER(10,0), 
	"ROWVERSION" RAW(16)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MYTABLESPACE" ;
--------------------------------------------------------
--  DDL for Index ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYSCHEMA"."ID_PK" ON "MYSCHEMA"."XXCL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MYTABLESPACE" ;
--------------------------------------------------------
--  DDL for Index XXCO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MYSCHEMA"."XXCO_PK" ON "MYSCHEMA"."XXCO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MYTABLESPACE" ;
--------------------------------------------------------
--  Constraints for Table XXCL
--------------------------------------------------------

  ALTER TABLE "MYSCHEMA"."XXCL" ADD CONSTRAINT "ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MYTABLESPACE"  ENABLE;
  ALTER TABLE "MYSCHEMA"."XXCL" MODIFY ("UPDATED" NOT NULL ENABLE);
  ALTER TABLE "MYSCHEMA"."XXCL" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "MYSCHEMA"."XXCL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table XXCO
--------------------------------------------------------

  ALTER TABLE "MYSCHEMA"."XXCO" ADD CONSTRAINT "XXCO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MYTABLESPACE"  ENABLE;
