SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[XXCL] (
    [ID]      UNIQUEIDENTIFIER NOT NULL,
    [NAME]    NVARCHAR (10)    NULL,
    [CREATED] DATETIME         NOT NULL,
    [UPDATED] DATETIME         NOT NULL
);


CREATE TABLE [dbo].[XXCO] (
    [ID]         UNIQUEIDENTIFIER NOT NULL,
    [VALUE]      INT              NOT NULL,
    [CREATED]    DATETIME         NOT NULL,
    [UPDATED]    DATETIME         NOT NULL,
    [ROWVERSION] UNIQUEIDENTIFIER NOT NULL
);
